### ISSUE TITLE
Display of breadcrumbs looks strange

### ISSUE THREAD

**Issue by swrobel** [abe33/atom-tree-view-breadcrumb#3]
Atom 0.141.0, Atom Light UI

![screen shot 2014-11-04 at 6 15 06 pm](https://cloud.githubusercontent.com/assets/157270/4911681/aec22e52-6491-11e4-941a-492f821f778c.png)

**Comment by kankaristo** [comment]
I took the style sheet above and made a very simplistic style for the breadcrumbs:
```
@import "ui-variables";

tree-view-breadcrumb {
  border-top: 1px solid @background-color-highlight;
  overflow-y: hidden;
  
  .tree-view-breadcrumb {
    .btn {
      transition: all 0.2s;
      
      // Clear button styles
      border: none;
      background: none;
      border-radius: 0 !important;
      
      // Set button text color
      color: @text-color;
      
      // Less padding
      padding: 0px 2px;
      
      // Extra padding to the first and last items
      &:first-child {
        padding-left: 5px;
      }
      &:last-child {
        padding-right: 10px;
      }
      
      // Move the project root icon down
      &.root {
        padding-top: 3px;
      }
      
      // Last button
      &.btn-primary {
        color: @text-color-highlight;
      }
      
      // Add a '/' before each directory (except the first one)
      &:not(:first-child):before {
        color: @text-color;
        content: '/';
      }
      
      // Hover style
      &:hover {
        color: @text-color-highlight;
        
        &:first-child {
          background: @background-color-highlight;
        }
        &:not(:first-child) {
          background-image: -webkit-linear-gradient(left, transparent 7px, @background-color-highlight 7px, @background-color-highlight 100%);
          background-image: linear-gradient(left, transparent 7px, @background-color-highlight 7px, @background-color-highlight 100%);
        }
      }
    }
  }
}
```

I'd like to add a short transition for the horizontal scroll (when the breadcrumb gets too wide), but I'm not sure if that can be done in pure Less/CSS.

I also get some weird pixel high artifacts, where the tree view is showing between the breadcrumb and its horizontal scroll bar.

**Comment by abe33** [comment]
Thanks @kankaristo, I'll try to make something by mixing your code with mine and see where it leads. 

As for the transition on scroll, AFAIK there's no such thing available in CSS, however, I programatically set the scroll so it could be done in JS.

**Comment by kankaristo** [comment]
@abe33: The "Path Style" breadcrumb has a small bug: if the breadcrumb gets too wide, it gets obscured by the scroll bar. Also, the rapid change in height while scrolling in the tree view is a little distracting. Maybe the scroll bar's height should be added to the total height whether it's visible or not?

![screenshot from 2015-06-04 23 04 36](https://cloud.githubusercontent.com/assets/3522333/7993336/24bdec7c-0b0e-11e5-9a1d-e94694ab12e2.png)

I also re-added my one pixel top-border, so that it looks a little smarter with [tree-view-open-files](https://atom.io/packages/tree-view-open-files).

**Comment by abe33** [comment]
>  the breadcrumb gets too wide, it gets obscured by the scroll bar

Yes, I haven't looked yet at how I could deal with that scrollbar thing. I hesitate between hiding it or making it a thin line at the bottom of the view like in the screen below:

![tree-view-breadcrumb_less_-__users_cedric_github_tree-view-breadcrumb_-_atom](https://cloud.githubusercontent.com/assets/247140/7994168/94efd81e-0b0b-11e5-89ee-062586eeaf0e.png)

Tell what you think about that.

>  Also, the rapid change in height while scrolling in the tree view is a little distracting

You mean when the breadcrumb appear? Because there's a setting to make it always visible.

> I also re-added my one pixel top-border, so that it looks a little smarter with tree-view-open-files.

That's why user stylesheets are for ;). I can't assume that everybody has `tree-view-open-file` in combination with `tree-view-breadcrumb`, even if like you I use both altogether, so I choosed to remove the border from your example.

**Comment by abe33** [comment]
BTW, if you want to try the thin line version you can use that code in your stylesheet, that's what I used to make the screen above: 

```css
tree-view-breadcrumb::-webkit-scrollbar {
    width: 1px;
    height: 1px;
}

tree-view-breadcrumb::-webkit-scrollbar-thumb {
    background-color: @text-color-subtle;
}

tree-view-breadcrumb::-webkit-scrollbar-track {
    background-color: @background-color-highlight;
}
```

**Comment by kankaristo** [comment]
> That's why user stylesheets are for ;).

True, agreed. :)

> You mean when the breadcrumb appear? Because there's a setting to make it always visible.

No, I actually have that enabled. I mean the height change when the scroll bar appears.

> I hesitate between hiding it or making it a thin line at the bottom of the view like in the screen below:

I really like it! But... Is it difficult to grab with the mouse cursor? I wouldn't really care, because my mouse has horizontal scrolling, but not all mice do. I guess the scrolling isn't strictly necessary though, since you can just click the directories to get to the root.

I can't get the above style sheets to work, the scroll bar doesn't change... :(

**Comment by kankaristo** [comment]
I have no idea why, but I had to add `!important` to all of the above (scroll bar height and colors).

`@text-color-subtle` is *too* subtle in my theme (doesn't show up at all). I'm using Atom Dark and Base16 Tomorrow Dark. How does `@text-color-highlight` look for you?

**Comment by kankaristo** [comment]
And to answer my earlier question: the 1px scroll bar is not too difficult to grab with the mouse. :)

**Comment by abe33** [comment]
> How does @text-color-highlight look for you?

Looks quite too bright for my taste, but there's no good solution here (it all depends of the theme).

> And to answer my earlier question: the 1px scroll bar is not too difficult to grab with the mouse. :)

Haha, I was wondering, I'm mostly on OSX now, with a magic mouse at work and the tarckpad at home, so I get an horizontal mouse wheel for free so I no longer drag the scrollbars :).

> I have no idea why, but I had to add !important to all of the above (scroll bar height and colors).

It' probably because of the theme you use, maybe it already define styles for scrollbars with a more specific selector.

**Comment by kankaristo** [comment]
> Looks quite too bright for my taste, but there's no good solution here (it all depends of the theme).

What about `@text-color`? Atom Dark UI is probably one of the most common UI themes, and the scroll bar is invisible with `@text-color-subtle` (seems to be the same as `@background-color-highlight`).

> I no longer drag scrollbars :).

Yeah, me neither, but I was thinking of an "average" user with an "average" mouse. :)

> It' probably because of the theme you use, maybe it already define styles for scrollbars with a more specific selector.

Atom Dark UI seems to have:
```
.scrollbars-visible-always /deep/ ::-webkit-scrollbar {...}
```

This works without `!important`):
```
tree-view-breadcrumb.path-style::-webkit-scrollbar {...}
```

**Comment by kankaristo** [comment]
Here's what I ended up using:
```
tree-view-breadcrumb.path-style, .tree-view-open-files ul, div.tree-view-scroller {
  &::-webkit-scrollbar:horizontal {
    height: 2px;
  }
  &::-webkit-scrollbar-thumb:horizontal {
    background: linear-gradient(@text-color, rgba(255, 255, 255, 0));
  }
  &::-webkit-scrollbar-track:horizontal {
    background: @background-color-highlight;
  }
}
```

It's an attempt to emulate a height of "one and a half" pixels. I added this style to all horizontal scroll bars in the tree view, and 1 pixel was a little bit too skinny, especially for the actual tree view, where the scroll bar is touching the edge of the window.

**Comment by abe33** [comment]
What do you think of making that a setting, one where you can choose whether to use the native scrollbar or the modified ones (maybe with some various styles, like a thin version, a version with bottom padding, etc)?

**Comment by kankaristo** [comment]
That would probably be best. I think that 2 versions is enough, a thin one (1 pixel) and a regular one, with extra bottom padding so it doesn't obscure the breadcrumb.

Everything else (like my 1.5 pixel version) should be left to `styles.less`.

**Comment by abe33** [comment]
Looks good to, I'll try to push something soon.
